
from dsf.messageprocessingpipeline import MessageProcessingPipeline
#from dsf.messageadapters import MessageInputAdapterAmqpConsumer, MessageOutputAdapterAmqpProducer, MessageOutputAdapterConsoleWriter